2024-03-06T09:57:43.4755482Z ##[group]Run tox
2024-03-06T09:57:43.4755989Z [36;1mtox[0m
2024-03-06T09:57:43.4786267Z shell: /usr/bin/bash -e {0}
2024-03-06T09:57:43.4786870Z env:
2024-03-06T09:57:43.4787322Z   pythonLocation: /opt/hostedtoolcache/Python/3.7.17/x64
2024-03-06T09:57:43.4787926Z   LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.7.17/x64/lib
2024-03-06T09:57:43.4789486Z ##[endgroup]
2024-03-06T09:57:43.6288931Z GLOB sdist-make: /home/runner/work/cassandraconnectorpkg/cassandraconnectorpkg/setup.py
2024-03-06T09:57:44.8664383Z python3.7 create: /home/runner/work/cassandraconnectorpkg/cassandraconnectorpkg/.tox/python3.7
2024-03-06T09:57:45.6192621Z ##[group]tox: python3.7
2024-03-06T09:57:45.6194031Z python3.7 installdeps: -rrequirements_dev.txt
2024-03-06T09:58:03.5439465Z python3.7 inst: /home/runner/work/cassandraconnectorpkg/cassandraconnectorpkg/.tox/.tmp/package/1/databaseautomation-0.0.1.zip
2024-03-06T09:58:06.0043881Z ##[error]ERROR: invocation failed (exit code 1), logfile: /home/runner/work/cassandraconnectorpkg/cassandraconnectorpkg/.tox/python3.7/log/python3.7-2.log
2024-03-06T09:58:06.0055691Z ================================== log start ===================================
2024-03-06T09:58:06.0057197Z Processing ./.tox/.tmp/package/1/databaseautomation-0.0.1.zip
2024-03-06T09:58:06.0058135Z   Installing build dependencies: started
2024-03-06T09:58:06.0059022Z   Installing build dependencies: finished with status 'done'
2024-03-06T09:58:06.0060019Z   Getting requirements to build wheel: started
2024-03-06T09:58:06.0061028Z   Getting requirements to build wheel: finished with status 'error'
2024-03-06T09:58:06.0061903Z   error: subprocess-exited-with-error
2024-03-06T09:58:06.0062648Z   
2024-03-06T09:58:06.0063405Z   × Getting requirements to build wheel did not run successfully.
2024-03-06T09:58:06.0064248Z   │ exit code: 1
2024-03-06T09:58:06.0064890Z   ╰─> [16 lines of output]
2024-03-06T09:58:06.0065515Z       Traceback (most recent call last):
2024-03-06T09:58:06.0067510Z         File "/home/runner/work/cassandraconnectorpkg/cassandraconnectorpkg/.tox/python3.7/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
2024-03-06T09:58:06.0069790Z           main()
2024-03-06T09:58:06.0071535Z         File "/home/runner/work/cassandraconnectorpkg/cassandraconnectorpkg/.tox/python3.7/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
2024-03-06T09:58:06.0073456Z           json_out['return_val'] = hook(**hook_input['kwargs'])
2024-03-06T09:58:06.0075808Z         File "/home/runner/work/cassandraconnectorpkg/cassandraconnectorpkg/.tox/python3.7/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
2024-03-06T09:58:06.0077653Z           return hook(config_settings)
2024-03-06T09:58:06.0079327Z         File "/tmp/pip-build-env-21an5tug/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
2024-03-06T09:58:06.0080998Z           return self._get_build_requires(config_settings, requirements=['wheel'])
2024-03-06T09:58:06.0082693Z         File "/tmp/pip-build-env-21an5tug/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
2024-03-06T09:58:06.0084173Z           self.run_setup()
2024-03-06T09:58:06.0085566Z         File "/tmp/pip-build-env-21an5tug/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 338, in run_setup
2024-03-06T09:58:06.0086836Z           exec(code, locals())
2024-03-06T09:58:06.0087640Z         File "<string>", line 41, in <module>
2024-03-06T09:58:06.0088461Z         File "<string>", line 12, in get_requirements
2024-03-06T09:58:06.0089576Z       FileNotFoundError: [Errno 2] No such file or directory: './requirements.txt'
2024-03-06T09:58:06.0090496Z       [end of output]
2024-03-06T09:58:06.0091001Z   
2024-03-06T09:58:06.0091814Z   note: This error originates from a subprocess, and is likely not a problem with pip.
2024-03-06T09:58:06.0092926Z error: subprocess-exited-with-error
2024-03-06T09:58:06.0094088Z 
2024-03-06T09:58:06.0094638Z × Getting requirements to build wheel did not run successfully.
2024-03-06T09:58:06.0095497Z │ exit code: 1
2024-03-06T09:58:06.0096135Z ╰─> See above for output.
2024-03-06T09:58:06.0096468Z 
2024-03-06T09:58:06.0097014Z note: This error originates from a subprocess, and is likely not a problem with pip.
2024-03-06T09:58:06.0098118Z 
2024-03-06T09:58:06.0098583Z [notice] A new release of pip available: 22.2.1 -> 24.0
2024-03-06T09:58:06.0099640Z [notice] To update, run: pip install --upgrade pip
2024-03-06T09:58:06.0100143Z 
2024-03-06T09:58:06.0100469Z =================================== log end ====================================
2024-03-06T09:58:06.0101268Z ___________________________________ summary ____________________________________
2024-03-06T09:58:06.0105927Z ##[error]ERROR:   python3.7: InvocationError for command /home/runner/work/cassandraconnectorpkg/cassandraconnectorpkg/.tox/python3.7/bin/python -m pip install --exists-action w .tox/.tmp/package/1/databaseautomation-0.0.1.zip (exited with code 1)
2024-03-06T09:58:06.0234617Z ##[error]Process completed with exit code 1.
